#!/bin/bash

set -e

# shellcheck disable=SC1090
. "$HOME"/.asdf/asdf.sh
# shellcheck disable=SC1090
. "$HOME"/.asdf/completions/asdf.bash

# ruff check
hatch fmt
# mypy check
hatch -e types run check
