name: Create PR (update version)

on:
  push:
#  workflow_dispatch:
#    inputs:
#      segment:
#        description: increment version method
#        type: string
#        required: true
#        options:
#          - major  # 1.0.0 to 2.0.0
#          - minor  # 1.0.0 to 1.1.0
#          - micro  # 1.0.0 to 1.0.1

env:
  branch-name: "version-update"

jobs:
  commit-and-push:
    name: Commit and push
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-version: ${{ steps.new-version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Configure git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create branch
        run: git checkout -b ${{ env.branch-name }} main

      - name: Update version
        run: hatch version micro

      - name: Get new version number
        id: new-version
        run: echo "version=$(hatch version)" >> $GITHUB_OUTPUT

      - name: Commit and push
        run: |
          git commit -am "build: update version to ${{ steps.new-version.outputs.version }}"
          git push --set-upstream origin ${{ env.branch-name }}

  create-pr:
    name: Create a PR
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs:
      - commit-and-push
    steps:
      - name: Create PR
        run: |
          gh pr create \
            --base main --head ${{ env.branch-name }} \
            --title "Update version to ${{ needs.commit-and-push.outputs.new-version }}" \
            --label "update version"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
