name: Publish to PyPI

on:
  release:
    types:
      - published

env:
  app-name: "chronovoyage"

jobs:
  check-tag-name-exists:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.tag_name != '' }}
    steps:
      - run: "true"

  publish-pip-package:
    needs: check-tag-name-exists
    uses: ./.github/workflows/publish-pip-package.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      id-token: write

  publish-docker-image:
    needs: check-tag-name-exists
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tag: ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  publish-docs:
    needs: check-tag-name-exists
    uses: ./.github/workflows/publish-docs.yml
    secrets:
      AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
    permissions:
      contents: read
      id-token: write
