name: Publish to PyPI

on:
  release:
    types:
      - published
  push:

env:
  app-name: "chronovoyage"

jobs:
  publish-pip-package:
#    if: ${{ github.event.release.tag_name != '' }}
    uses: ./.github/workflows/publish-pip-package.yml
    with:
      tag: v0.2.0.dev2  # ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      id-token: write

  publish-docker-image:
#    if: ${{ github.event.release.tag_name != '' }}
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tag: v0.2.0.dev2  # ${{ github.event.release.tag_name }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

  publish-docs:
#    if: ${{ github.event.release.tag_name != '' }}
    uses: ./.github/workflows/publish-docs.yml
    permissions:
      contents: read
      id-token: write
