name: Publish to PyPI

on:
  release:
    types:
      - published
  push:

env:
  app-name: "chronovoyage"

jobs:
  download-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download assets
        uses: robinraju/release-downloader@v1
        with:
          tag: v0.2.0.dev2  # ${{ github.event.release.tag_name }}
          fileName: ${{ env.app-name }}-*
          out-file-path: dist

      - name: List files
        run: |
          ls -la dist

  publish:
    if: false
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build Package
        run: hatch build -c

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
