name: Publish to PyPI

on:
  release:
    types:
      - published

env:
  app-name: "chronovoyage"

jobs:
  check-tag-name-exists:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.tag_name != '' }}
    steps:
      - run: "true"

  publish-pip-package:
    needs: check-tag-name-exists
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish
        run: gh workflow run publish-pip-package.yml --ref ${{ github.event.release.tag_name }}

  publish-docker-image:
    needs: check-tag-name-exists
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish
        run: gh workflow run publish-docker-image.yml --ref ${{ github.event.release.tag_name }}

  publish-docs:
    needs: check-tag-name-exists
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish
        run: gh workflow run publish-docs.yml --ref ${{ github.event.release.tag_name }}
